import { Type } from 'class-transformer';
import { ArrayNotEmpty, IsArray, IsBoolean, IsIn, IsInt, IsISO8601, IsOptional, IsString, IsUUID, Max, MaxLength, Min, MinLength, ValidateNested } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class LoginDto { @IsString() @MinLength(1) @MaxLength(1024) @ApiProperty({ type: String, format: 'password' }) password!: string; }
export class AuthorizeAccountDto {
  @IsString() @MinLength(1) @MaxLength(50) @ApiProperty({ type: String }) connectorType!: string;
  @IsString() @MinLength(1) @MaxLength(200) @ApiProperty({ type: String }) platformId!: string;
  @IsOptional() @IsString() @MaxLength(200) @ApiPropertyOptional({ type: String }) displayName?: string;
  @IsString() @MinLength(1) @MaxLength(10_000) @ApiProperty({ type: String, writeOnly: true }) secret!: string;
  @IsString() @MinLength(1) @MaxLength(50) @ApiProperty({ type: String }) kind!: string;
}
export class ReauthorizeAccountDto { @IsString() @MinLength(1) @MaxLength(10_000) @ApiProperty({ type: String, writeOnly: true }) secret!: string; @IsString() @MinLength(1) @MaxLength(50) @ApiProperty({ type: String }) kind!: string; }
export class DeleteAccountDto { @IsOptional() @IsBoolean() @ApiPropertyOptional({ type: Boolean, default: true }) retainData?: boolean; }
export class CreateJobDto { @IsUUID() @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; }
export class PaginationQueryDto { @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) cursor?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(200) @ApiPropertyOptional({ type: Number, default: 50 }) limit?: number; }
export class AccountQueryDto extends PaginationQueryDto { @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) accountId?: string; }
export class CommentQueryDto extends AccountQueryDto {
  @IsOptional() @IsArray() @ArrayNotEmpty() @IsUUID(undefined, { each: true }) @ApiPropertyOptional({ type: [String], format: 'uuid' }) accountIds?: string[];
  @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) noteId?: string;
  @IsOptional() @IsISO8601({ strict: true, strictSeparator: true }) @ApiPropertyOptional({ type: String, format: 'date-time' }) from?: string;
  @IsOptional() @IsISO8601({ strict: true, strictSeparator: true }) @ApiPropertyOptional({ type: String, format: 'date-time' }) to?: string;
}
export class DashboardQueryDto { @IsOptional() @IsIn(['daily', 'weekly', 'monthly']) @ApiPropertyOptional({ type: String, enum: ['daily', 'weekly', 'monthly'] }) period?: string; }
export class PushKeysDto { @IsString() @MinLength(1) @MaxLength(4096) @ApiProperty({ type: String }) p256dh!: string; @IsString() @MinLength(1) @MaxLength(4096) @ApiProperty({ type: String }) auth!: string; }
export class PushSubscriptionRequestDto { @IsUUID() @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @IsString() @MaxLength(4096) @ApiProperty({ type: String, format: 'uri' }) endpoint!: string; @ValidateNested() @Type(() => PushKeysDto) @ApiProperty({ type: PushKeysDto }) keys!: PushKeysDto; }
export class NotificationQueryDto extends PaginationQueryDto { @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) accountId?: string; }

export class PageInfoDto { @ApiProperty({ type: String, nullable: true }) nextCursor!: string | null; @ApiProperty({ type: Boolean }) hasMore!: boolean; }
export class ConnectorCapabilityDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String }) capability!: string; @ApiProperty({ type: Boolean }) enabled!: boolean; @ApiProperty({ type: String, format: 'date-time' }) checkedAt!: string; }
export class AccountDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String }) connectorType!: string; @ApiProperty({ type: String }) platformId!: string; @ApiProperty({ type: String, nullable: true }) displayName!: string | null; @ApiProperty({ type: String, format: 'date-time' }) createdAt!: string; @ApiProperty({ type: String, format: 'date-time' }) updatedAt!: string; @ApiProperty({ type: [ConnectorCapabilityDto] }) capabilities!: ConnectorCapabilityDto[]; }
export class SyncJobDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, nullable: true }) externalJobId!: string | null; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String }) status!: string; @ApiProperty({ type: String }) currentStage!: string; @ApiProperty({ type: String }) verificationStatus!: string; @ApiProperty({ type: String, format: 'date-time', nullable: true }) startedAt!: string | null; @ApiProperty({ type: String, format: 'date-time', nullable: true }) completedAt!: string | null; @ApiProperty({ type: String, nullable: true }) error!: string | null; @ApiProperty({ type: String, format: 'date-time' }) createdAt!: string; @ApiProperty({ type: Object, nullable: true, additionalProperties: true }) payload!: object | null; }
export class NoteDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String }) connectorType!: string; @ApiProperty({ type: String }) platformId!: string; @ApiProperty({ type: String }) title!: string; @ApiProperty({ type: String, format: 'date-time' }) publishedAt!: string; @ApiProperty({ type: String, format: 'date-time' }) firstSeenAt!: string; @ApiProperty({ type: String, format: 'date-time' }) lastSeenAt!: string; @ApiProperty({ type: String, format: 'date-time' }) createdAt!: string; @ApiProperty({ type: String, format: 'date-time' }) updatedAt!: string; }
export class CommentDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid', nullable: true }) noteId!: string | null; @ApiProperty({ type: String }) connectorType!: string; @ApiProperty({ type: String }) platformId!: string; @ApiProperty({ type: String, nullable: true }) parentPlatformId!: string | null; @ApiProperty({ type: String }) content!: string; @ApiProperty({ type: String, format: 'date-time' }) publishedAt!: string; @ApiProperty({ type: String, format: 'date-time' }) firstSeenAt!: string; @ApiProperty({ type: String, format: 'date-time' }) lastSeenAt!: string; @ApiProperty({ type: Number }) likeCount!: number; @ApiProperty({ type: String }) source!: string; }
export class ReportMetricDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) reportId!: string; @ApiProperty({ type: String, format: 'uuid' }) metricDefinitionId!: string; @ApiProperty({ type: String }) availability!: string; @ApiProperty({ type: String, nullable: true }) value!: string | null; }
export class ReportDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String }) reportType!: string; @ApiProperty({ type: String, format: 'date-time' }) periodStart!: string; @ApiProperty({ type: String, format: 'date-time' }) periodEnd!: string; @ApiProperty({ type: Number }) version!: number; @ApiProperty({ type: String }) status!: string; @ApiProperty({ type: [String] }) missingDates!: string[]; @ApiProperty({ type: Object, additionalProperties: true }) missingFields!: unknown; @ApiProperty({ type: String, nullable: true }) backfillId!: string | null; @ApiProperty({ type: String, nullable: true }) rebuildJobId!: string | null; @ApiProperty({ type: String, format: 'uuid', nullable: true }) previousReportId!: string | null; @ApiProperty({ type: String, nullable: true }) rebuildReason!: string | null; @ApiProperty({ type: String, format: 'date-time' }) generatedAt!: string; @ApiProperty({ type: [ReportMetricDto] }) metrics!: ReportMetricDto[]; }
export class NotificationDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String }) eventId!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String }) type!: string; @ApiProperty({ type: String }) title!: string; @ApiProperty({ type: String }) body!: string; @ApiProperty({ type: String }) link!: string; @ApiProperty({ type: String, format: 'date-time', nullable: true }) readAt!: string | null; @ApiProperty({ type: String, format: 'date-time' }) createdAt!: string; }
export class DashboardCardDto { @ApiProperty({ type: String }) key!: string; @ApiProperty({ type: String, nullable: true }) value!: string | null; @ApiProperty({ type: String }) availability!: string; }
export class DashboardResponseDto { @ApiProperty({ type: String }) period!: string; @ApiProperty({ type: [DashboardCardDto] }) cards!: DashboardCardDto[]; }
export class AuthCsrfResponseDto { @ApiProperty({ type: String }) csrfToken!: string; }
export class AuthLoginResponseDto extends AuthCsrfResponseDto { @ApiProperty({ type: Number }) expiresIn!: number; }
export class OkResponseDto { @ApiProperty({ type: Boolean }) ok!: boolean; }
export class AccountStateDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: Boolean }) active!: boolean; }
export class AccountDeletionDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: Boolean }) retainedBusinessData!: boolean; @ApiProperty({ type: Boolean }) credentialsDeleted!: boolean; @ApiProperty({ type: Boolean }) officialRevocationSupported!: boolean; }
export class PushSubscriptionResponseDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String, format: 'uri' }) endpoint!: string; }
export class BackgroundExportDto { @ApiProperty({ type: String, format: 'uuid' }) jobId!: string; @ApiProperty({ type: [String], format: 'uuid' }) jobIds!: string[]; }
export class PaginatedResponseDto { @ApiProperty({ type: 'array', items: { type: 'object' } }) items!: unknown[]; @ApiProperty({ type: PageInfoDto }) pageInfo!: PageInfoDto; }
export class ErrorDto { @ApiProperty({ type: Number }) statusCode!: number; @ApiProperty({ type: String }) message!: string; }
