import { Type } from 'class-transformer';
import { ArrayNotEmpty, IsArray, IsBoolean, IsIn, IsInt, IsISO8601, IsOptional, IsString, IsUUID, Max, MaxLength, Min, MinLength, ValidateNested } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class LoginDto { @IsString() @MinLength(1) @MaxLength(1024) @ApiProperty({ type: String, format: 'password' }) password!: string; }
export class AuthorizeAccountDto {
  @IsString() @MinLength(1) @MaxLength(50) @ApiProperty({ type: String }) connectorType!: string;
  @IsString() @MinLength(1) @MaxLength(200) @ApiProperty({ type: String }) platformId!: string;
  @IsOptional() @IsString() @MaxLength(200) @ApiPropertyOptional({ type: String }) displayName?: string;
  @IsString() @MinLength(1) @MaxLength(10_000) @ApiProperty({ type: String, writeOnly: true }) secret!: string;
  @IsString() @MinLength(1) @MaxLength(50) @ApiProperty({ type: String }) kind!: string;
}
export class ReauthorizeAccountDto { @IsString() @MinLength(1) @MaxLength(10_000) @ApiProperty({ type: String, writeOnly: true }) secret!: string; @IsString() @MinLength(1) @MaxLength(50) @ApiProperty({ type: String }) kind!: string; }
export class DeleteAccountDto { @IsOptional() @IsBoolean() @ApiPropertyOptional({ type: Boolean, default: true }) retainData?: boolean; }
export class CreateJobDto { @IsUUID() @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; }
export class LocalCollectorSyncDto { @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) accountId?: string; }
export class PaginationQueryDto { @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) cursor?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(200) @ApiPropertyOptional({ type: Number, default: 50 }) limit?: number; }
export class AccountQueryDto extends PaginationQueryDto { @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) accountId?: string; @IsOptional() @IsIn(['xiaohongshu', 'douyin']) @ApiPropertyOptional({ type: String, enum: ['xiaohongshu', 'douyin'] }) platform?: 'xiaohongshu' | 'douyin'; }
export class CommentQueryDto extends AccountQueryDto {
  @IsOptional() @IsArray() @ArrayNotEmpty() @IsUUID(undefined, { each: true }) @ApiPropertyOptional({ type: [String], format: 'uuid' }) accountIds?: string[];
  @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) noteId?: string;
  @IsOptional() @IsISO8601({ strict: true, strictSeparator: true }) @ApiPropertyOptional({ type: String, format: 'date-time' }) from?: string;
  @IsOptional() @IsISO8601({ strict: true, strictSeparator: true }) @ApiPropertyOptional({ type: String, format: 'date-time' }) to?: string;
  @IsOptional() @IsString() @MaxLength(200) @ApiPropertyOptional({ type: String }) keyword?: string;
  @IsOptional() @IsIn(['true']) @ApiPropertyOptional({ type: String, enum: ['true'] }) newOnly?: string;
}
export class DashboardQueryDto { @IsOptional() @IsIn(['daily', 'weekly', 'monthly']) @ApiPropertyOptional({ type: String, enum: ['daily', 'weekly', 'monthly'] }) period?: string; @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) accountId?: string; @IsOptional() @IsIn(['official', 'self-scrape']) @ApiPropertyOptional({ type: String, enum: ['official', 'self-scrape'], default: 'official' }) source?: string; }
export class PushKeysDto { @IsString() @MinLength(1) @MaxLength(4096) @ApiProperty({ type: String }) p256dh!: string; @IsString() @MinLength(1) @MaxLength(4096) @ApiProperty({ type: String }) auth!: string; }
export class PushSubscriptionRequestDto { @IsUUID() @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @IsString() @MaxLength(4096) @ApiProperty({ type: String, format: 'uri' }) endpoint!: string; @ValidateNested() @Type(() => PushKeysDto) @ApiProperty({ type: PushKeysDto }) keys!: PushKeysDto; }
export class NotificationQueryDto extends PaginationQueryDto { @IsOptional() @IsUUID() @ApiPropertyOptional({ type: String, format: 'uuid' }) accountId?: string; }

export class PageInfoDto { @ApiProperty({ type: String, format: 'uuid', nullable: true }) nextCursor!: string | null; @ApiProperty({ type: Boolean }) hasMore!: boolean; }
export class ConnectorCapabilityDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String }) capability!: string; @ApiProperty({ type: Boolean }) enabled!: boolean; @ApiProperty({ type: String, format: 'date-time' }) checkedAt!: string; }
export class AccountDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, enum: ['xiaohongshu', 'douyin'] }) platform!: string; @ApiProperty({ type: String }) source!: string; @ApiProperty({ type: String }) connectorType!: string; @ApiProperty({ type: String }) platformId!: string; @ApiProperty({ type: String, nullable: true }) xhsAccountId!: string | null; @ApiProperty({ type: String, nullable: true }) displayName!: string | null; @ApiProperty({ type: String, format: 'uri', nullable: true }) avatarUrl!: string | null; @ApiProperty({ type: String, format: 'date-time', nullable: true }) identityVerifiedAt!: string | null; @ApiProperty({ type: String, format: 'date-time' }) createdAt!: string; @ApiProperty({ type: String, format: 'date-time' }) updatedAt!: string; @ApiProperty({ type: [ConnectorCapabilityDto] }) capabilities!: ConnectorCapabilityDto[]; }
export class SyncJobDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, nullable: true }) externalJobId!: string | null; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String, enum: ['pending', 'running', 'succeeded', 'failed'] }) status!: string; @ApiProperty({ type: String, enum: ['authorize', 'notes', 'metrics', 'comments', 'replies', 'complete', 'export_comments'] }) currentStage!: string; @ApiProperty({ type: String, enum: ['verified', 'unverifiable'] }) verificationStatus!: string; @ApiProperty({ type: String, format: 'date-time', nullable: true }) startedAt!: string | null; @ApiProperty({ type: String, format: 'date-time', nullable: true }) completedAt!: string | null; @ApiProperty({ type: String, nullable: true }) error!: string | null; @ApiProperty({ type: String, format: 'date-time' }) createdAt!: string; @ApiProperty({ type: Object, nullable: true, additionalProperties: true }) payload!: object | null; }
export class NoteAccountDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, enum: ['xiaohongshu', 'douyin'] }) platform!: string; @ApiProperty({ type: String, nullable: true }) displayName!: string | null; @ApiProperty({ type: String }) platformId!: string; }
export class NoteMetricDto { @ApiProperty({ type: String }) key!: string; @ApiProperty({ type: String }) displayName!: string; @ApiProperty({ type: String, enum: ['zero', 'not_synced', 'awaiting_authorization', 'not_provided', 'available'] }) availability!: string; @ApiProperty({ type: String, nullable: true }) value!: string | null; @ApiProperty({ type: String }) source!: string; @ApiProperty({ type: String, format: 'date-time' }) observedAt!: string; @ApiProperty({ type: String, format: 'date-time' }) capturedAt!: string; @ApiProperty({ type: String }) definitionVersion!: string; }
export class NoteCommentCompletenessDto { @ApiProperty({ type: String }) status!: string; @ApiProperty({ type: String, nullable: true }) error!: string | null; @ApiProperty({ type: String, format: 'date-time' }) updatedAt!: string; }
export class NoteDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String }) connectorType!: string; @ApiProperty({ type: String }) platformId!: string; @ApiProperty({ type: String }) title!: string; @ApiProperty({ type: String, format: 'date-time' }) publishedAt!: string; @ApiProperty({ type: String, format: 'date-time' }) firstSeenAt!: string; @ApiProperty({ type: String, format: 'date-time' }) lastSeenAt!: string; @ApiProperty({ type: String, format: 'date-time' }) createdAt!: string; @ApiProperty({ type: String, format: 'date-time' }) updatedAt!: string; @ApiProperty({ type: NoteAccountDto }) account!: NoteAccountDto; @ApiProperty({ type: [NoteMetricDto] }) metrics!: NoteMetricDto[]; @ApiProperty({ type: NoteCommentCompletenessDto, nullable: true }) commentCompleteness!: NoteCommentCompletenessDto | null; }
export class CommentDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid', nullable: true }) noteId!: string | null; @ApiProperty({ type: String }) connectorType!: string; @ApiProperty({ type: String }) platformId!: string; @ApiProperty({ type: String, nullable: true }) parentPlatformId!: string | null; @ApiProperty({ type: String }) content!: string; @ApiProperty({ type: String, format: 'date-time' }) publishedAt!: string; @ApiProperty({ type: String, format: 'date-time' }) firstSeenAt!: string; @ApiProperty({ type: String, format: 'date-time' }) lastSeenAt!: string; @ApiProperty({ type: Number }) likeCount!: number; @ApiProperty({ type: String }) source!: string; }
export class ReportMetricDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) reportId!: string; @ApiProperty({ type: String, format: 'uuid' }) metricDefinitionId!: string; @ApiProperty({ type: String, enum: ['zero', 'not_synced', 'awaiting_authorization', 'not_provided', 'available'] }) availability!: string; @ApiProperty({ type: String, nullable: true }) value!: string | null; }
export class MissingReportFieldDto { @ApiProperty({ type: String, format: 'uuid' }) noteId!: string; @ApiProperty({ type: String, format: 'uuid', nullable: true }) metricDefinitionId!: string | null; @ApiProperty({ type: String, format: 'date' }) date!: string; @ApiPropertyOptional({ type: String }) metricKey?: string; @ApiPropertyOptional({ type: String, enum: ['metric_definition_missing', 'aggregation_unavailable', 'metric_definition_transition'] }) reason?: string; }
export class ReportEvidenceRefDto { @ApiProperty({ type: String, format: 'uuid' }) snapshotId!: string; @ApiProperty({ type: Number, minimum: 1 }) revision!: number; }
export class ReportDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String, enum: ['daily', 'weekly', 'monthly'] }) reportType!: string; @ApiProperty({ type: String, format: 'date-time' }) periodStart!: string; @ApiProperty({ type: String, format: 'date-time' }) periodEnd!: string; @ApiProperty({ type: Number }) version!: number; @ApiProperty({ type: String, enum: ['complete', 'awaiting_data'] }) status!: string; @ApiProperty({ type: String, enum: ['complete', 'legacy_incomplete'] }) provenanceStatus!: string; @ApiProperty({ type: 'array', items: { type: 'string', format: 'date' } }) missingDates!: string[]; @ApiProperty({ type: [MissingReportFieldDto] }) missingFields!: MissingReportFieldDto[]; @ApiProperty({ type: [ReportEvidenceRefDto] }) evidenceRefs!: ReportEvidenceRefDto[]; @ApiProperty({ type: String, nullable: true }) backfillId!: string | null; @ApiProperty({ type: String, nullable: true }) rebuildJobId!: string | null; @ApiProperty({ type: String, format: 'uuid', nullable: true }) previousReportId!: string | null; @ApiProperty({ type: String, nullable: true }) rebuildReason!: string | null; @ApiProperty({ type: String, format: 'date-time' }) generatedAt!: string; @ApiProperty({ type: [ReportMetricDto] }) metrics!: ReportMetricDto[]; }
export class NotificationDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String }) eventId!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String, enum: ['sync_completed', 'sync_failed', 'authorization_expired', 'new_comment', 'comment_sync_incomplete', 'report_generated', 'report_rebuilt'] }) type!: string; @ApiProperty({ type: String }) title!: string; @ApiProperty({ type: String }) body!: string; @ApiProperty({ type: String }) link!: string; @ApiProperty({ type: String, format: 'date-time', nullable: true }) readAt!: string | null; @ApiProperty({ type: String, format: 'date-time' }) createdAt!: string; }
export class DashboardCardDto { @ApiProperty({ type: String }) key!: string; @ApiProperty({ type: String, enum: ['cumulative_delta', 'sum_interval', 'period_end', 'deduplicated_period'] }) aggregation!: string; @ApiProperty({ type: String, nullable: true }) value!: string | null; @ApiProperty({ type: String, enum: ['zero', 'not_synced', 'awaiting_authorization', 'not_provided', 'available'] }) availability!: string; }
export class DashboardTrendPointDto { @ApiProperty({ type: String, format: 'date' }) date!: string; @ApiProperty({ type: [DashboardCardDto] }) metrics!: DashboardCardDto[]; }
export class DashboardMetricDeltaDto { @ApiProperty({ type: String }) key!: string; @ApiProperty({ type: String, nullable: true }) value!: string | null; @ApiProperty({ type: String, enum: ['zero', 'not_synced', 'awaiting_authorization', 'not_provided', 'available'] }) availability!: string; }
export class DashboardDailyRowDto { @ApiProperty({ type: String, format: 'date' }) date!: string; @ApiProperty({ type: [DashboardCardDto] }) metrics!: DashboardCardDto[]; @ApiProperty({ type: [DashboardMetricDeltaDto] }) deltas!: DashboardMetricDeltaDto[]; }
export class DashboardRankedNoteDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String }) title!: string; @ApiProperty({ type: String, format: 'date-time' }) publishedAt!: string; @ApiProperty({ type: String }) metricKey!: string; @ApiProperty({ type: String }) metricLabel!: string; @ApiProperty({ type: String }) value!: string; }
export class DashboardResponseDto {
  @ApiProperty({ type: String, enum: ['daily', 'weekly', 'monthly'] }) period!: string;
  @ApiProperty({ type: String, format: 'date-time' }) periodStart!: string;
  @ApiProperty({ type: String, format: 'date-time' }) periodEnd!: string;
  @ApiProperty({ type: String, nullable: true }) source!: string | null;
  @ApiProperty({ type: String, format: 'date-time', nullable: true }) lastSyncedAt!: string | null;
  @ApiProperty({ type: [DashboardCardDto] }) cards!: DashboardCardDto[];
  @ApiProperty({ type: [DashboardTrendPointDto] }) trend!: DashboardTrendPointDto[];
  @ApiProperty({ type: [DashboardDailyRowDto] }) dailyRows!: DashboardDailyRowDto[];
  @ApiProperty({ type: [DashboardRankedNoteDto] }) rankedNotes!: DashboardRankedNoteDto[];
}
export class AuthCsrfResponseDto { @ApiProperty({ type: String }) csrfToken!: string; }
export class AuthLoginResponseDto extends AuthCsrfResponseDto { @ApiProperty({ type: Number }) expiresIn!: number; }
export class OkResponseDto { @ApiProperty({ type: Boolean }) ok!: boolean; }
export class AccountStateDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: Boolean }) active!: boolean; }
export class AccountDeletionDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: Boolean }) retainedBusinessData!: boolean; @ApiProperty({ type: Boolean }) credentialsDeleted!: boolean; @ApiProperty({ type: Boolean }) officialRevocationSupported!: boolean; }
export class PushSubscriptionResponseDto { @ApiProperty({ type: String, format: 'uuid' }) id!: string; @ApiProperty({ type: String, format: 'uuid' }) accountId!: string; @ApiProperty({ type: String, format: 'uri' }) endpoint!: string; }
export class BackgroundExportDto { @ApiProperty({ type: String, format: 'uuid' }) jobId!: string; @ApiProperty({ type: [String], format: 'uuid' }) jobIds!: string[]; }
export class SettingsAccountDto { @ApiProperty({ type: String }) displayName!: string; @ApiProperty({ type: String, nullable: true }) xhsAccountId!: string | null; @ApiProperty({ type: String }) platformId!: string; @ApiProperty({ type: String, format: 'uri', nullable: true }) avatarUrl!: string | null; @ApiProperty({ type: String, enum: ['authenticated'] }) loginState!: string; }
export class SettingsStatusDto { @ApiProperty({ type: String, enum: ['healthy', 'unhealthy', 'disabled'] }) api!: string; @ApiProperty({ type: String, enum: ['healthy', 'unhealthy', 'disabled'] }) database!: string; @ApiProperty({ type: String, enum: ['healthy', 'unhealthy', 'disabled'] }) collector!: string; @ApiProperty({ type: SettingsAccountDto, nullable: true }) account!: SettingsAccountDto | null; @ApiProperty({ type: String }) version!: string; @ApiProperty({ type: String, enum: ['Asia/Shanghai'] }) timezone!: string; }
export class PaginatedResponseDto { @ApiProperty({ type: 'array', items: { type: 'object' } }) items!: unknown[]; @ApiProperty({ type: PageInfoDto }) pageInfo!: PageInfoDto; }
export class ErrorDto { @ApiProperty({ type: Number }) statusCode!: number; @ApiProperty({ type: String }) message!: string; }
